title: "cypher's notepad"
description: "TIS : Today I Saljiled"
email: encyphered@gmail.com
tagline: logging.getLogger('sapjil')
baseurl: /blog
paginate: 1
google_analytics: "UA-31683453-1"

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
